### ISSUE TITLE
sudo dnf system-upgrade download --releasever=28  Cannot download rfremix-release-28-0.1

### ISSUE THREAD

**Issue by gendalph** [RussianFedora/rfremix-release#3]
[MIRROR] rfremix-release-28-0.1.noarch.rpm: Status code: 404 for https://mirror.yandex.ru/fedora/russianfedora/russianfedora/branding/fedora/development/28/x86_64/os/rfremix-release-28-0.1.noarch.rpm            
[MIRROR] rfremix-release-28-0.1.noarch.rpm: Status code: 404 for http://ftp.tigro.info/fedora/russianfedora/russianfedora/branding/fedora/development/28/x86_64/os/rfremix-release-28-0.1.noarch.rpm               
[MIRROR] rfremix-release-28-0.1.noarch.rpm: Status code: 404 for http://ftp.russianfedora.pro/fedora/russianfedora/russianfedora/branding/fedora/development/28/x86_64/os/rfremix-release-28-0.1.noarch.rpm        
[FAILED] rfremix-release-28-0.1.noarch.rpm: No more mirrors to try - All mirrors were already tried without success                                                                                                
(2715-2716/2724): rfremix-logos-26.0.1-1.fc27.R.x86_64.rpm                             99% [=====================================================================================-] 930 kB/s | 2.5 GB     00:12 ETA
Загруженные пакеты были сохранены в кэше до следующей успешной транзакции.
Вы можете удалить кэшированные пакеты выполнив «dnf clean packages».
Ошибка: Ошибка при загрузке пакетов:
  Cannot download rfremix-release-28-0.1.noarch.rpm: All mirrors were tried

**Comment by Tigro** [comment]
Должно быть сейчас уже исправлено.
