### ISSUE TITLE
мастер первоначальной настройки зацикливается

### ISSUE THREAD

**Issue by chipitsine** [RussianFedora/rfremix-release#4]
добрый день!

правильное ли это место, чтобы открывать баги ?
в 28-м образе есть баг, у него бесконечный цикл в мастере первоначальной настройки

**Comment by Vascom** [comment]
Место не правильное, но сойдёт.
Баг поправлен в этом образе http://koji.russianfedora.pro/kojifiles/work/tasks/80/70080/RFRemix-Workstation-Live-x86_64-28-1.4.iso

**Comment by chipitsine** [comment]
круто. но не совсем понятно, как должны это узнать пользователи.
я иду на официальный сайт, качаю официальный образ (который, оказывается, не полностью рабочий) .... и надо включить телепатию, чтобы понять, где правильный образ ? ))

**Comment by chipitsine** [comment]
кстати, а какое место правильное ?
я искал по официальному сайту упоминание трекера или форума, не нашел ничего, поэтому пришел сюда

**Comment by Vascom** [comment]
Тот, кто может выложить образ на зеркала в отпуске. Но, вроде, скоро должен всё сделать.
Правильное место - багтрекер http://redmine.russianfedora.pro/ и группа в телеграме. Они указаны, например тут (в анонсе релиза RFRemix 28) https://ru.fedoracommunity.org/posts/vyshel-rfremix-28/

**Comment by chipitsine** [comment]
я не читал анонсы.
я пошел на официальный сайт, там ссылок нет.

ладно, буду иметь в виду про redmine, спасибо

**Comment by Vascom** [comment]
Пожалуйста :)
